root: false

extends:
    - 'plugin:@autoguru/base'

env:
    browser: true
    node: true

overrides:
    - files: ['**/*.ts', '**/*.tsx']
      extends:
          - 'plugin:@autoguru/typescript'
      parser: '@typescript-eslint/parser'
      rules:
          '@typescript-eslint/ban-ts-ignore': 'off'
      parserOptions:
          tsconfigRootDir: './packages/utilities/'
