root: false

extends:
    - 'plugin:@autoguru/base'

env:
    browser: true
    node: true

overrides:
    - files: ['**/*.{ts,tsx}', '*.ts']
      rules:
          unicorn/no-process-exit: off # TODO: Investigate why this rule cant exist at the root
          '@typescript-eslint/no-var-requires': off
          '@typescript-eslint/ban-ts-ignore': 'off'
          'unicorn/prefer-node-protocol': 'off'
      parser: '@typescript-eslint/parser'
      parserOptions:
          tsconfigRootDir: './packages/gdu/'
