root: false

env:
    browser: true
    node: true

rules:
    unicorn/no-process-exit: off
    no-await-in-loop: off

overrides:
    - files: ['**/*.{ts,tsx}', '*.ts']
      extends:
          - 'plugin:@autoguru/typescript'
      rules:
          unicorn/no-process-exit: off # TODO: Investigate why this rule cant exist at the root
          sonarjs/cognitive-complexity: warn
          sonarjs/no-nested-template-literals: warn
          '@typescript-eslint/no-var-requires': off
          '@typescript-eslint/ban-ts-ignore': 'off'
          'unicorn/prefer-node-protocol': 'off'
      parser: '@typescript-eslint/parser'
      parserOptions:
          tsconfigRootDir: './packages/gdu/'
