name: Claude Assistant
on:
    issue_comment:
        types: [created]
    pull_request_review_comment:
        types: [created]
    issues:
        types: [opened, assigned, labeled]
    pull_request_review:
        types: [submitted]

jobs:
    claude-response:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: read
            issues: write
            pull-requests: write
            id-token: write
        steps:
            - uses: anthropics/claude-code-action@v1
              with:
                  anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
