name: SonarQube CI

on: push

jobs:
  test:
    name: SonarQube for TypeScript
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Brisbane
      CI: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Node.js version from package.json
        run: |
          NODE_VERSION=$(jq -r '.volta.node' package.json)
          if [ -z "$NODE_VERSION" ]; then
            echo "Error: No Node.js version found in package.json under .volta.node"
            exit 1
          fi
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --no-cache --ci --coverage

      - name: Fix lcov paths
        run: |
          echo "Fixing paths in lcov.info..."
          sed -i 's#\.\./##g' coverage/lcov.info
          echo "Fixed lcov.info paths:"
          head -n 20 coverage/lcov.info

      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner

      - name: Run SonarQube analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey="${{ github.event.repository.name }}" \
            -Dsonar.sources=packages \
            -Dsonar.exclusions="**/node_modules/**,**/stories/**,**/*.stories.tsx" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
